# Articles

In [66]:
import pandas as pd

def load_data():
    article_table = pd.read_json("../data/cache/testsentimentanalysis_partial/documents.json")
    return article_table

In [67]:
articles = load_data()
articles

                source                                               text
0             Atlantic  A Los Angeles news anchor said earlier this mo...
1      National Review  President Obama and GOP House speaker Paul Rya...
2     Business Insider  ’  ’ ”   A mass exodus was underway at the Sta...
3      Washington Post       Alabama Supreme Court Chief Justice Roy M...
4              Reuters   Brazilian President Michel Temer gave his ble...
5      Washington Post       “Mothers from miles around worried about ...
6        Buzzfeed News  ’Read the order:’] A federal judge in Texas ha...
7      Washington Post       Within two days of landing in Istanbul, t...
8              Reuters   The start of a new round of peace talks on th...
9            Breitbart  A math teacher at a San Diego high school has ...
10            Guardian  A quest taken up by farmers and independent re...
11                 NPR  A Syrian   went into effect at sundown on Mond...
12       New York Post  The Seahawks are sending a message as a team f...
13           Breitbart  During a January 5 speech in which President O...
14           Breitbart  Longtime radio host and Fox News personality A...
15           Breitbart  TORONTO (AP)  —   Toronto police say they are ...
16     Washington Post            An Ohio police chief and two nursing...
17            Guardian  The Uber passenger said he wanted to give a ti...
18            Fox News  SEATTLE TEACHERS WEARING ’BLACK LIVES MATTER’ ...
19       New York Post  The Staten Island dad who  on his birthday lat...
20           Breitbart  COLOGNE, Germany: A peaceful protest turned vi...
21       New York Post  Getting your Costco fix will soon require a lo...
22             Reuters   An equally divided federal appeals court refu...
23            Atlantic  , I want to receive updates from partners and ...
24             Reuters   The White House said on Monday that coalition...
25             Reuters  Transactions in commercial property fell by 40...
26             Reuters   Voters in four states raised minimum wages on...
27           Breitbart  During MSNBC’s coverage of the shooting of pol...
28      New York Times  At work, propped against a wall, near piles of...
29            Atlantic  #DeploraBall crowd pics pic. twitter.  If any ...
...                ...                                                ...
4970  Business Insider  ’’ ”The Jalisco Nueva Generación cartel  —   o...
4971               CNN  London (CNN) An investigation is underway afte...
4972           Reuters   President Barack Obama chastised supporters a...
4973           Reuters   Before he left Russia at the end of 2014, Say...
4974           Reuters   China’s South China Sea military deployments ...
4975  Business Insider  ’   Rejoice! Google has finally added     trip...
4976               NPR  The skies cleared just in time for Derby fans ...
4977         Breitbart  (THE UNITED WEST) The United West investigativ...
4978         Breitbart  More than 160 Simon and Schuster children’s bo...
4979   National Review  Cedar Rapids, Iowa  —   Senator Bernie Sanders...
4980               NPR  After Rubi Ibarra’s father invited ”everybody”...
4981          Guardian  Almost 150 civilians have been killed in a wee...
4982         Breitbart    actor Leonardo DiCaprio has in recent years ...
4983  Business Insider  ’Ross Stores has been deemed a ”retail treasur...
4984     New York Post  As the most popular syndicated show on TV, wit...
4985               Vox   Set aside, for a moment, Donald Trump’s wholl...
4986     New York Post          A Rochester man risked his life to sav...
4987               Vox   It seems like such an elegant solution. Milli...
4988   Washington Post       Some cynics on the right and certainly th...
4989         Breitbart  Bloomberg’s Stephanie Baker and Tim Higgins wr...
4990   National Review  I have been following the Trump camp in recent...
4991     New York Post  Eli Weaver called himself “Amish Stud” on Moco...
4992  Business Insider  ’  ’ ”   Days before President Donald Trump’s ...
4993    New York Times  MANILA  —   The Philippines’ highest court rul...
4994     Buzzfeed News   In a bid to blunt a nationwide opioid drug ad...
4995           Reuters   President Donald Trump and Republican leaders...
4996   Washington Post       President Trump’s decision to delegate au...
4997         Breitbart  At a community college in California last week...
4998         Breitbart  LONDON (AP)  —   Royal Air Force fighter jets ...
4999     New York Post  An Alabama mother allegedly sent images of her...

[5000 rows x 2 columns]

# AS_Vec

In [68]:
as_df = pd.read_json("../data/cache/testsentimentanalysis_partial/as_vectors/doc_as_vectors.json")
as_df

,0,1,2,3,4,5,6,7,8,9,...,4412,4413,4414,4415,4416,4417,4418,4419,4420,4421
0,0.0,0.000,0.500,0.000,0.0,0.0,0.375,1.125,-0.5,0.25,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0
1,0.0,0.000,0.000,0.000,0.0,0.0,0.000,0.000,0.0,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0
2,0.0,0.000,0.000,0.000,0.0,0.0,0.000,0.000,0.0,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0
3,0.0,0.000,0.000,-0.250,0.0,0.0,0.000,0.000,0.0,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0
4,0.0,-0.125,0.000,0.000,0.0,0.0,0.000,0.000,0.0,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0
5,0.0,0.000,0.000,0.000,0.0,0.0,0.000,0.000,0.0,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0
6,0.0,0.000,0.000,0.000,0.0,0.0,0.000,0.000,0.0,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0
7,0.0,0.000,0.000,-0.250,0.0,0.0,0.125,0.000,0.0,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0
8,0.0,0.000,0.000,0.000,0.0,0.0,0.000,0.000,0.0,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0
9,0.0,0.000,0.000,0.000,0.0,0.0,0.000,0.000,0.0,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0
10,0.0,0.000,0.000,0.000,0.0,0.0,0.000,0.000,0.0,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0
11,0.0,-0.250,0.000,0.000,0.0,0.0,0.000,0.000,0.0,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0
12,0.0,0.000,0.000,0.000,0.0,0.0,0.000,0.000,0.0,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0
13,0.0,0.000,0.000,0.000,0.0,0.0,0.000,0.000,0.0,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0
14,0.0,-0.125,0.000,0.000,0.0,0.0,0.000,0.000,0.0,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0
15,0.0,0.000,0.000,0.000,0.0,0.0,0.000,0.000,0.0,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0
16,0.0,0.000,0.000,0.000,0.0,0.0,0.000,0.000,0.0,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0
17,0.0,0.000,0.000,0.000,0.0,0.0,0.000,0.000,0.0,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0
18,0.0,0.000,0.000,0.000,0.0,0.0,0.000,0.000,0.0,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0
19,0.0,0.000,0.000,0.000,0.0,0.0,0.000,0.000,0.0,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0
20,0.0,0.000,0.000,0.000,0.0,0.0,0.000,0.000,0.0,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0
21,0.0,0.000,0.000,0.000,0.0,0.0,0.000,0.000,0.0,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0
22,0.0,0.000,0.000,0.000,0.0,0.0,0.000,0.000,0.0,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0
23,0.0,-0.125,-0.125,0.000,0.0,0.0,0.000,0.000,0.0,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0
24,0.0,0.000,0.000,0.000,0.0,0.0,0.000,0.000,0.0,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0
25,0.0,0.000,0.000,0.000,0.0,0.0,0.000,0.000,0.0,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0
26,0.0,0.000,0.000,0.000,0.0,0.0,0.000,0.000,0.0,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0
27,0.0,0.000,0.000,0.000,0.0,0.0,0.000,0.000,0.0,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0
28,0.0,0.000,0.000,0.000,0.0,0.0,0.000,0.000,0.0,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0
29,0.0,0.000,0.000,0.000,0.0,0.0,0.000,0.000,0.0,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4970,0.0,0.000,0.000,0.000,0.0,0.0,0.000,0.000,0.0,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0
4971,0.0,-0.625,0.000,0.000,0.0,0.0,0.750,0.000,0.0,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0
4972,0.0,0.000,0.000,0.000,0.0,0.0,0.000,0.000,0.0,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0
4973,0.0,0.000,0.000,0.000,0.0,0.0,0.000,0.000,0.0,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0
4974,0.0,0.000,0.000,0.000,-0.5,0.0,0.000,0.000,0.0,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0
4975,0.0,0.000,0.000,0.000,0.0,0.0,0.000,0.000,0.0,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0
4976,0.0,0.000,0.000,0.000,0.0,0.0,0.000,0.000,0.0,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0
4977,0.0,0.000,0.000,0.000,0.0,0.0,0.000,0.000,0.0,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0
4978,0.0,0.000,0.000,0.000,0.0,0.0,0.000,0.000,0.0,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0
4979,0.0,-0.125,0.000,0.000,0.0,0.0,0.000,0.000,0.0,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0
4980,0.0,0.000,0.000,0.000,0.0,0.0,0.000,0.000,0.0,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0
4981,0.0,0.000,0.000,0.000,0.0,0.0,0.000,0.000,0.0,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-0.625,0.0,0.0
4982,0.0,0.000,0.000,0.000,0.0,0.0,0.000,0.000,0.0,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0
4983,0.0,0.000,0.000,0.000,0.0,0.0,0.000,0.000,0.0,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0
4984,0.0,0.000,0.000,0.000,0.0,0.0,0.000,0.000,0.0,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0
4985,0.0,0.000,0.000,0.000,0.0,0.0,0.000,0.000,0.0,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0
4986,0.0,0.000,0.000,0.000,0.0,0.0,0.000,0.000,0.0,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0
4987,0.0,0.000,0.000,0.000,0.0,0.0,0.000,0.000,0.0,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0
4988,0.0,0.000,0.000,0.000,0.0,0.0,0.000,0.000,0.0,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0
4989,0.0,0.000,0.000,0.000,0.0,0.0,0.000,0.000,0.0,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0
4990,0.0,0.750,0.000,0.000,0.0,0.0,0.000,0.000,0.0,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-0.500,0.0,0.0
4991,0.0,0.000,0.000,0.000,0.0,0.0,0.000,0.000,0.0,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0
4992,0.0,0.000,0.000,0.000,0.0,0.0,0.000,0.000,0.0,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0
4993,0.0,0.000,0.000,0.000,0.0,0.0,0.000,0.000,0.0,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0
4994,0.0,0.000,0.000,0.000,0.0,0.0,0.000,0.000,0.0,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0
4995,0.0,0.000,0.000,0.125,0.0,0.0,0.000,0.000,0.0,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0
4996,0.0,0.000,0.000,0.000,0.0,0.0,0.000,0.000,0.0,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0
4997,0.0,0.000,0.000,0.000,0.0,0.0,0.000,0.000,0.0,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0
4998,0.0,0.000,0.000,0.000,0.0,0.0,0.000,0.000,0.0,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0
4999,0.0,0.000,0.000,0.000,0.0,0.0,0.000,0.000,0.0,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0

In [69]:
as_df.describe()

,0,1,2,3,4,5,6,7,8,9,...,4412,4413,4414,4415,4416,4417,4418,4419,4420,4421
count,5000.000000,5000.000000,5000.00000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,...,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000
mean,-0.000400,-0.010646,-0.00015,-0.018325,-0.000742,-0.000079,0.006975,0.000800,-0.000529,0.000725,...,-0.000275,-0.000075,-0.000325,0.000300,-0.000025,-0.000175,-0.000025,-0.000675,0.000100,-0.000075
std,0.039609,0.264280,0.02332,0.101492,0.078190,0.046700,0.176223,0.032685,0.069079,0.020067,...,0.021287,0.014897,0.032163,0.027043,0.014254,0.010753,0.015714,0.021858,0.015208,0.013347
min,-0.750000,-8.750000,-0.87500,-1.500000,-0.875000,-2.000000,-2.500000,-0.750000,-1.500000,-0.375000,...,-0.875000,-0.500000,-1.250000,-0.625000,-0.500000,-0.625000,-0.625000,-0.625000,-0.750000,-0.500000
25%,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
max,0.750000,2.125000,0.75000,1.250000,1.000000,1.000000,2.250000,1.125000,1.875000,0.750000,...,0.375000,0.500000,1.000000,1.000000,0.750000,0.125000,0.375000,0.375000,0.625000,0.500000

In [70]:
#as_df.idxmax
print(as_df.max().max())
print(as_df.max().idxmax())

19.5
1726

In [71]:
as_df[1725].max()

0.75

In [72]:
print(as_df.min().min())
print(as_df.min().idxmin())

-64.5
31

try to rank rows by their abs value of min/max

In [73]:
maximum_sentiment = as_df.loc[:, as_df.max().sort_values(ascending=False).index]
maximum_sentiment.max()

1726    19.500
3651    14.750
460      7.750
348      7.500
516      6.875
214      6.750
406      6.250
65       6.000
2207     5.875
41       5.250
1611     4.875
865      4.875
2361     4.875
212      4.875
814      4.625
3206     4.500
3625     4.375
1009     4.250
124      4.125
1397     4.125
782      4.125
306      3.875
225      3.750
904      3.750
353      3.750
1935     3.750
4039     3.750
1053     3.625
522      3.625
4358     3.625
         ...
620      0.000
2545     0.000
2951     0.000
955      0.000
2952     0.000
3823     0.000
1557     0.000
3005     0.000
4067     0.000
4077     0.000
691      0.000
3789     0.000
1603     0.000
1608     0.000
2656     0.000
2655     0.000
1613     0.000
1937     0.000
2653     0.000
2651     0.000
3580     0.000
1003     0.000
1212     0.000
1208     0.000
2584     0.000
2548     0.000
4159     0.000
3099     0.000
2308     0.000
3469     0.000
Length: 4422, dtype: float64

In [74]:
minimum_sentiment = as_df.loc[:, as_df.min().sort_values(ascending=True).index]
minimum_sentiment.min()

31     -64.500
79      -9.625
1       -8.750
2098    -7.250
110     -7.000
3190    -7.000
214     -6.750
21      -6.500
131     -6.375
1010    -6.250
236     -6.125
1074    -5.750
406     -5.625
522     -5.250
3562    -5.250
2471    -5.000
367     -5.000
294     -5.000
1228    -4.750
3643    -4.612
727     -4.500
2070    -4.500
327     -4.375
4133    -4.375
4198    -4.375
73      -4.375
263     -4.375
217     -4.375
1930    -4.375
896     -4.375
         ...
348      0.000
2920     0.000
2163     0.000
2908     0.000
1854     0.000
4109     0.000
3202     0.000
3238     0.000
3402     0.000
3392     0.000
3387     0.000
1596     0.000
4002     0.000
4003     0.000
4004     0.000
4005     0.000
4009     0.000
3440     0.000
701      0.000
1713     0.000
1714     0.000
1715     0.000
1716     0.000
661      0.000
3269     0.000
3268     0.000
1749     0.000
1763     0.000
691      0.000
1447     0.000
Length: 4422, dtype: float64

Try to find maximum distance between maximum and minimum

In [75]:
(as_df.max() - as_df.min()).max()

66.5

In [76]:
distance_sentiment = as_df.loc[:, (as_df.max() - as_df.min()).sort_values(ascending=False).index]
distance_sentiment.describe()

,31,1726,3651,214,79,406,1,460,110,522,...,1448,1462,2496,3469,1447,3141,3660,1749,2537,2543
count,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,...,5000.0,5000.0,5000.0,5000.0,5000.0,5000.0,5000.0,5000.0,5000.0,5000.0
mean,-0.019172,0.004275,0.014825,-0.009925,-0.039982,-0.013391,-0.010646,-0.018475,-0.004386,-0.004925,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
std,0.924773,0.278815,0.258499,0.215758,0.429385,0.375688,0.264280,0.209184,0.127078,0.156872,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
min,-64.500000,-0.750000,-0.625000,-6.750000,-9.625000,-5.625000,-8.750000,-2.125000,-7.000000,-5.250000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
25%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
50%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
75%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
max,2.000000,19.500000,14.750000,6.750000,3.375000,6.250000,2.125000,7.750000,2.375000,3.625000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

How many aspects have 0 sentiment?

In [77]:
((as_df.max() - as_df.min()) == 5).value_counts()

False    4406
True       16
dtype: int64

# Aspect data

In [78]:
import json
with open('../data/cache/testsentimentanalysis_partial/aspects/aspects.json', 'r') as in_file:
    aspect_data = json.load(in_file)

In [79]:
list(aspect_data.keys())[215]

'roy'